POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "name": "Rahul",
  "email": "rahul@gmail.com",
  "password": "12345"
}
###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email":"avishkar@gmail.com",
  "password":"12345"
}
###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "groupName": "Goa Trip"
}
###
POST http://localhost:8080/api/group-members
Content-Type: application/json

{
  "userId": 2,
  "groupId": 1
}
###
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "groupId":1,
  "paidBy":1,
  "amount":8000,
  "description":"Lunch",
  "splitType": "EQUAL"
}
###
POST http://localhost:8080/api/splits
Content-Type: application/json

{
  "expenseId": 1,
  "userId": 1,
  "amountOwed": 2500
}
###
GET http://localhost:8080/api/expenses/group/2
###
GET http://localhost:8080/api/splits/expense/3
###
GET http://localhost:8080/api/group-members/1
###
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "groupId": 1,
  "paidBy": 1,
  "amount": 6000,
  "description": "Dinner Exact",
  "splitType": "EXACT",
  "splits": [
    {
      "userId": 1,
      "amount": 4000
    },
    {
      "userId": 2,
      "amount": 2000
    }
  ]
}
###
GET http://localhost:8080/api/splits/expense/3
###
###
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "groupId": 1,
  "paidBy": 1,
  "amount": 900,
  "description": "Restaurant",
  "splitType": "ITEM_WISE",

  "items": [
    {
      "itemName": "Burger",
      "price": 300,
      "userIds": [1]
    },
    {
      "itemName": "Pizza",
      "price": 400,
      "userIds": [2]
    },
    {
      "itemName": "Fries",
      "price": 200,
      "userIds": [1,2]
    }
  ]
}
###
###
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "groupId": 1,
  "paidBy": 1,
  "amount": 900,
  "description": "Restaurant",
  "splitType": "ITEM_WISE",

  "items": [
    {
      "itemName": "Burger",
      "price": 300,
      "userIds": [1]
    },
    {
      "itemName": "Pizza",
      "price": 400,
      "userIds": [2]
    },
    {
      "itemName": "Fries",
      "price": 200,
      "userIds": [1,2]
    }
  ]
}
###
GET http://localhost:8080/api/splits/balance/1
###
###
POST http://localhost:8080/api/splits/settle
Content-Type: application/json

{
  "fromUserId": 2,
  "toUserId": 1,
  "amount": 500
}
###
POST http://localhost:8080/api/expenses
Content-Type: application/json

{
  "groupId": 1,
  "paidBy": 1,
  "amount": 1100,
  "description": "Restaurant",
  "splitType": "ITEM_WISE",
  "items": [
    {
      "itemName": "Pizza",
      "price": 600,
      "userIds": [1,2]
    },
    {
      "itemName": "Burger",
      "price": 300,
      "userIds": [2]
    },
    {
      "itemName": "Cold Drink",
      "price": 200,
      "userIds": [1]
    }
  ]
}
###
###
GET http://localhost:8080/api/expenses/group/1
###
###
DELETE http://localhost:8080/api/expenses/7
###
###
PUT http://localhost:8080/api/expenses/1
Content-Type: application/json

{
  "amount": 5500,
  "description": "Goa Hotel Updated"
}
###
GET http://localhost:8080/api/dashboard/1